//
// THIS IS A GENERATED FILE, DO NOT EDIT
//
// Generated by gen.sh
//

var urlmap = [
  ["*://mail.google.com/chat/*", "chat"],
  ["*://mail.google.com/sharing/*", "chat"],
  ["*://mail.google.com/mail/*", "gmail"],
  ["*://mail.google.com/mail/*", "gmail_condensed"],
  ["*://calendar.google.com/*", "calendar"],
  ["*://chat.google.com/*", "chat"],
  ["*://contacts.google.com/*", "contacts"],
  ["*://groups.google.com/*", "groups"],
  ["*://www.instagram.com/*", "instagram"],
  ["*://jamboard.google.com/*", "jamboard"],
  ["*://keep.google.com/*", "keep"],
  ["*://app.slack.com/*", "slack"],
  ["*://web.telegram.org/*", "telegram"],
  ["*://web.whatsapp.com/*", "whatsapp"],
  ["*://github.com/*", "github"],
  ["*://instagram.com/*", "instagram"]];

function Url2Mod(url) {
  const mods = ["chat", "chat", "gmail", "gmail_condensed", "calendar", "chat", "contacts", "groups", "instagram", "jamboard", "keep", "slack", "telegram", "whatsapp", "github", "instagram"];
  const re = new RegExp(`^(.*?://mail\.google\.com/chat/.*?)|(.*?://mail\.google\.com/sharing/.*?)|(.*?://mail\.google\.com/mail/.*?)|(.*?://mail\.google\.com/mail/.*?)|(.*?://calendar\.google\.com/.*?)|(.*?://chat\.google\.com/.*?)|(.*?://contacts\.google\.com/.*?)|(.*?://groups\.google\.com/.*?)|(.*?://www\.instagram\.com/.*?)|(.*?://jamboard\.google\.com/.*?)|(.*?://keep\.google\.com/.*?)|(.*?://app\.slack\.com/.*?)|(.*?://web\.telegram\.org/.*?)|(.*?://web\.whatsapp\.com/.*?)|(.*?://github\.com/.*?)|(.*?://instagram\.com/.*?)$`);
  let match = url.match(re);
  return match ? mods[[...match].splice(1).findIndex(x => !!x)] : null;
}

function Url2Mods(url) {
  const mods = ["chat", "chat", "gmail", "gmail_condensed", "calendar", "chat", "contacts", "groups", "instagram", "jamboard", "keep", "slack", "telegram", "whatsapp", "github", "instagram"];
  const regs = [new RegExp("`.*?://mail\.google\.com/chat/.*?"), new RegExp("`.*?://mail\.google\.com/sharing/.*?"), new RegExp("`.*?://mail\.google\.com/mail/.*?"), new RegExp("`.*?://mail\.google\.com/mail/.*?"), new RegExp("`.*?://calendar\.google\.com/.*?"), new RegExp("`.*?://chat\.google\.com/.*?"), new RegExp("`.*?://contacts\.google\.com/.*?"), new RegExp("`.*?://groups\.google\.com/.*?"), new RegExp("`.*?://www\.instagram\.com/.*?"), new RegExp("`.*?://jamboard\.google\.com/.*?"), new RegExp("`.*?://keep\.google\.com/.*?"), new RegExp("`.*?://app\.slack\.com/.*?"), new RegExp("`.*?://web\.telegram\.org/.*?"), new RegExp("`.*?://web\.whatsapp\.com/.*?"), new RegExp("`.*?://github\.com/.*?"), new RegExp("`.*?://instagram\.com/.*?")];
  let ret = new Set();
  for (let i = 0; i < regs.length; i++) {
    if (url.match(regs[i]))
      ret.add(mods[i]);
  }
  return ret;
}

