//
// THIS IS A GENERATED FILE, DO NOT EDIT
//
// Generated by gen.sh
//

var urlmap = [
  ["*://mail.google.com/chat/*", "chat"],
  ["*://mail.google.com/mail/*", "gmail"],
  ["*://mail.google.com/sharing/*", "chat"],
  ["*://chat.google.com/*", "chat"],
  ["*://contacts.google.com/*", "contacts"],
  ["*://groups.google.com/*", "groups"],
  ["*://jamboard.google.com/*", "jamboard"],
  ["*://keep.google.com/*", "keep"],
  ["*://web.telegram.org/*", "telegram"],
  ["*://web.whatsapp.com/*", "whatsapp"],
  ["*://www.instagram.com/*", "instagram"],
  ["*://instagram.com/*", "instagram"]];

function Url2Mod(url) {
  const mods = ["chat", "gmail", "chat", "chat", "contacts", "groups", "jamboard", "keep", "telegram", "whatsapp", "instagram", "instagram"];
  const re = new RegExp(`^(.*?://mail\.google\.com/chat/.*?)|(.*?://mail\.google\.com/mail/.*?)|(.*?://mail\.google\.com/sharing/.*?)|(.*?://chat\.google\.com/.*?)|(.*?://contacts\.google\.com/.*?)|(.*?://groups\.google\.com/.*?)|(.*?://jamboard\.google\.com/.*?)|(.*?://keep\.google\.com/.*?)|(.*?://web\.telegram\.org/.*?)|(.*?://web\.whatsapp\.com/.*?)|(.*?://www\.instagram\.com/.*?)|(.*?://instagram\.com/.*?)$`);
  let match = url.match(re);
  return match ? mods[[...match].splice(1).findIndex(x => !!x)] : null;
}

