//
// THIS IS A GENERATED FILE, DO NOT EDIT
//
// Generated by gen.sh
//

var modules_map = {
  "calendar": calendar,
  "chat": chat,
  "contacts": contacts,
  "github": github,
  "gmail": gmail,
  "groups": groups,
  "instagram": instagram,
  "jamboard": jamboard,
  "keep": keep,
  "slack": slack,
  "telegram": telegram,
  "whatsapp": whatsapp,
};
