//
// THIS IS A GENERATED FILE, DO NOT EDIT
//
// Generated by gen.sh
//

var modules = [
  calendar,
  chat,
  contacts,
  github,
  gmail,
  gmail_condensed,
  groups,
  instagram,
  jamboard,
  keep,
  slack,
  telegram,
  whatsapp,
];
